spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/c_auth_microservice?serverTimezone=America/Guayaquil
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  zipkin:
    base-url: http://localhost:9411
  application:
    name: alx-auth

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update  # dev
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true    # dev

jwt:
  secret: SomeStrongSecretForJWT

server:
  port: 3000

