version: '3.9'

services:
  prometheus:
    image: prom/prometheus:v2.47.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus

    # spring app in HOST and prometheus in Docker
    network_mode: host

    ports:
      - 9090:9090
    restart: always

volumes:
  prometheus_data: {}
  grafana_data: {}
